{% set year = "2018" %}
{% set cycle = "1" %}
{% set version ="0" %}

package:
  name: 11-id-chx-collection
  version: {{ year }}C{{ cycle }}.{{ version }}

build:
  number: 1

requirements:
  run:
    - chxtools
    - eiger-io
    - hxntools
    - pyserial
