{% set year = "2018" %}
{% set cycle = "2" %}
{% set version ="0" %}

package:
  name: 11-id-chx-analysis
  version: {{ year }}C{{ cycle }}.{{ version }}

build:
  number: 0

requirements:
  run:
    - chxtools
    - eiger-io
    - hdf5-lz4
    - chxanalys
    - dask
    - theano
    - graphviz
    - boto3
    - reportlab
