{% set year = "17" %}
{% set cycle = "Q1" %}
{% set version ="0" %}

package:
  name: 11-id-chx-analysis
  version: {{ year }}{{ cycle }}.{{ version }}

build:
  number: 1

requirements:
  run:
    - chxtools
    - eiger-io
    - hdf5-lz4
    - chxanalys
    - dask
    - theano
    - graphviz
    - boto3
    - reportlab
    - pytables
